name: Deploy Vue.js App

on:
  push:
    branches:
      - master # Déclenche le déploiement sur un push vers la branche master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Installer les dépendances
      - name: Install dependencies
        run: npm ci

      # 4. Build du projet
      - name: Build Vue.js app
        run: npm run build

      # 5. Déployer sur Apache2
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: 81.241.109.28
          username: joachim18
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd /var/www/html/your-project
            rm -rf *
            scp -r dist/* .
